#!/bin/bash/
#
##kasutaja lisamise skript
if [ $# -ne 1 ]; then
	echo "kasutusjuhend: $0 failinimi"
else
  failinimi=$1
  if [ -f $failinimi -a -r $failinimi ]; then
	echo "fail on korras"
	for rida in $(cat $failinimi)
	do
	  # faili sisu nähtav, kui fail on kättesaadav ja echo asemel vajalik skript
	kasutajanimi=$(echo "$rida" | cut -f1 -d:)
	sh lisa_kasutaja $kasutajanimi
	echo "$rida" | chpasswd # antud rida võimaldav kasutajale määrata vastav parool
	done
     else
	echo "probleem failiga $failinimi"
     fi
# parameetrite kontrolli lõpp
fi
